version: '3.1'
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - ./data-volume:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build:
    context: ./
    args:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app/
    ports:
      - ${PORT}:${PORT}
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
